<img src="vr.png" width="400" alt="DALLE 2" />
<h1>all of these pics were generated by DALLE 2 </h1>
<img src="vr1.png" width="400" alt="DALLE 2" />
<h1>kinda cool right?</h1>
<img src="vr2.png" width="400" alt="DALLE 2" />
<h1>it's a generative model that can generate images from text</h1>
<img src="vr3.png" width="400" alt="DALLE 2" />
<h1>it's trained on a dataset of 1.2 million images and even some of the code was generated by the a similar model called GTP-3....</h1>